### ISSUE TITLE
BLTxPT registers

### ISSUE THREAD

**Issue by dirkwhoffmann** [h5n1xp/Omega#26]
I've noticed the following in SAE: 

    bltapt = ((bltapt & 0xffff0000) | (v & 0xfffe)) >>> 0;

This line is executed when the low byte of the Blitter A Ptr is written to. As you can see, SAE deletes the lowest bit immediately.

In Omega, the lowest bit is usually cleared when bltapt ist read, but not always. In `blitter_execute`, you compute the D value via

    int D = (int16_t)chipset->bltapt; 

D gets a different value if the lowest bit is set. 

I think it's best to mimic SAE and clear the bit immediately in `bltapthL`. Same for the B, C, and D pointers.

**Comment by h5n1xp** [comment]
I think what SAE is doing is to ensure the pointers are word aligned. Am I corrrct?

If so, you will notice in Chipset.h the the function bltXpt(uint16_t value) shifts the pointer value right one place. As my blitter only sees the memory as a 16bit word array. So this shouldn’t be an issue.

Have I misunderstood? I hope my blitter code is wrong as that might fix a few problems 😊

**Comment by h5n1xp** [comment]
No!! You have found a huge bug I think!!! I don’t shift my register values if the register is written with a 32bit write!! 

I can’t believe I never saw this before

**Comment by dirkwhoffmann** [comment]
Yes, I didn't mentioned above that I was talking about the 32 bit writes. 

The following should do, I guess: 

    void bltapthL(uint32_t value){ 
        chipset.bltapt = value & ~1;
    }

**Comment by dirkwhoffmann** [comment]
"bltXpt(uint16_t value) shifts the pointer value right one place."

Are you talking about this function? (I cannot find a shift). 

    void bltbptl(uint16_t value){
        chipset.bltbpt =  value  | (chipset.bltbpt & 0xFFFF0000);//using the new 32bit register
    }

Shouldn't it be as follows? 

    void bltbptl(uint16_t value){
        chipset.bltbpt =  (value & 0xFFFE) | (chipset.bltbpt & 0xFFFF0000);//using the new 32bit register
    }

**Comment by h5n1xp** [comment]
You are correct, I was getting confused. When I added the line mode I moved the shift into the area copy mode setup as line mode uses the pointer registers as values... 

Ok, I need to investigate this properly later!

**Comment by h5n1xp** [comment]
Sorry I haven’t been able to look into this yet. As you might know, my country is in a bit of a mess at the moment, and I’m trying to convince our xenophobic dictator of a leader to Revoke Article 50 🙄

**Comment by mithrendal** [comment]
Yes, it is a real tragedy. My deepest feelings are now with the 48%.

**Comment by h5n1xp** [comment]
> Yes, it is a real tragedy. My deepest feelings are now with the 48%.

Thank you, half my friends are from Germany and Belgium. I was happy as a European, and being able to visit them easily.

**Comment by h5n1xp** [comment]
Ok,

> int D = (int16_t)chipset->bltapt; 

Is only used in line mode, if I clear the lowest bit, it reduces the accuracy of the lines drawn and looks a bit off when compared to a real amiga... my line draw mode is probably not exactly the same as the real blitter anyway (since I wrote it by trial and error). 

I'll keep the line draw as it is for now, since it took me weeks to get it working and I don't want to alter it unless I have to.

**Comment by dirkwhoffmann** [comment]
> I'll keep the line draw as it is for now

I also think that the line Blitter (which I have stolen for vAmiga 🙄) is good enough for now. 

If you want to replace it later, please have a look at WinFellow. They have a Fast Blitter (which is simpler than the cycle-accurate one) that supports all line modes. I think it shouldn't be too difficult to port their code.

**Comment by h5n1xp** [comment]
> > I'll keep the line draw as it is for now
> 
> I also think that the line Blitter (which I have stolen for vAmiga 🙄) is good enough for now.

Excellent 👍🏻 The amount of effort it took to get it to work, I would be pretty upset if you didn’t use it 😂 Perhaps, you might want to think about how one might add a single pixel per scanline mode to it? I don’t think it will be too difficult... but I’m not touching that code for a long while. Also I can’t quite think how to add the fill modes to the Area copy Blitter. I’ve made two attempts neither really worked.

> 
> If you want to replace it later, please have a look at WinFellow. They have a Fast Blitter (which is simpler than the cycle-accurate one) that supports all line modes. I think it shouldn't be too difficult to port their code.

I did look at the Fellow blitter code when I was trying to make my own, but I just couldn’t follow it at all. Which is why I wrote mine from scratch.

**Comment by dirkwhoffmann** [comment]
> Also I can’t quite think how to add the fill modes to the Area copy Blitter.

This shouldn't be too difficult. When I read the HRM first, I thought it's best to create a lookup table for mapping unfilled bit patterns to filled ones. The table would be too big for 16-bit values, but small enough for 8-bit values. For all bytes, there will be two table entries. Example: 

    --1---1-  maps to -- 11111- (first table) and 111---11 (second table) 

The first table is used when the fill flipflop (some bool variable) is off (meaning that the first bit is not in the fill area). The second table is used when the fill flipflop is on.

When I looked at WinFellow later, I saw that they are doing exactly the same. Hence, I think the table lookup approach seems to be the straight forward way to go.

**Comment by h5n1xp** [comment]
From the HRM the fill happens after the copy, shift and logic function so, I'm not sure how a LUT would work (since there might be a pattern in D which needs to be written to memory, inside/outside the lines).

http://amigadev.elowar.com/read/ADCD_2.1/Hardware_Manual_guide/node0122.html

My original idea was to check if channel C (which  I assume to be the pre-blit destination) was non zero, and then run a loop to copy in the bits (bit by bit) from my channel D calculation to the memory as required...

**Comment by dirkwhoffmann** [comment]
Yes, the fill logic is applied just after the Minterm logic:

![blitter](https://user-images.githubusercontent.com/12561945/55179057-fd617180-5186-11e9-8a48-b9fae4253129.gif)

Hence, if fill is enabled, you apply the fill pattern to the word coming out of the minterm logic unit. You need an additional boolean variable that keeps track if the bit of the end of the current byte is inside or outside.
